# Generated by Django 5.0.2 on 2024-05-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('seller_type', models.CharField(max_length=255)),
                ('date_first_added', models.DateField(auto_now_add=True)),
                ('ad_platform', models.CharField(max_length=255)),
            ],
        ),
    ]
