# Generated by Django 5.0.2 on 2024-05-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertplatform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='ad_platform',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='seller',
            name='domain',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
